version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "getPost-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iwyx4bmzserl"
s3_prefix = "getPost-test"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
